version: '3'

networks:
  services:
    ipam:
      config:
        - subnet: 173.17.0.0/24

services:
  #
  # Webserver
  #
  webserver:
    image: indy-node
    build:
      context: .
      dockerfile: pool.dockerfile
    command: 'bash -c ''./scripts/start_webserver.sh'''
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - HOST=173.17.0.100
      - RUST_LOG=${RUST_LOG}
    networks:
      services:
        ipv4_address: 173.17.0.100
    ports:
      - 9000:8000
    depends_on:
      - node1
      - node2
      - node3
      - node4
    volumes:
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      - node1-data:/home/indy/.mnt/node1
      - node2-data:/home/indy/.mnt/node2
      - node3-data:/home/indy/.mnt/node3
      - node4-data:/home/indy/.mnt/node4

  #
  # Nodes
  #
  node1:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 1'''
    networks:
      services:
        ipv4_address: 173.17.0.101
    ports:
      - 9701:9701
      - 9702:9702
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
#      - HOST=173.17.0.101
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node1-data:/home/indy/ledger

  node2:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 2'''
    networks:
      services:
        ipv4_address: 173.17.0.102
    ports:
      - 9703:9703
      - 9704:9704
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
      - RUST_LOG=${RUST_LOG}
#      - HOST=173.17.0.102
    volumes:
      - node2-data:/home/indy/ledger

  node3:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 3'''
    networks:
      services:
        ipv4_address: 173.17.0.103
    ports:
      - 9705:9705
      - 9706:9706
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
#      - HOST=173.17.0.103
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node3-data:/home/indy/ledger

  node4:
    image: indy-node
    command: 'bash -c ''./scripts/start_node.sh 4'''
    networks:
      services:
        ipv4_address: 173.17.0.104
    ports:
      - 9707:9707
      - 9708:9708
    environment:
      - IP=173.17.0.101
      - IPS=173.17.0.101,173.17.0.102,173.17.0.103,173.17.0.104
#      - HOST=173.17.0.104
      - RUST_LOG=${RUST_LOG}
    volumes:
      - node4-data:/home/indy/ledger

  #
  # Agents
  #
  alice:
    image: indy-agentjs
    build:
      context: .
      dockerfile: agent.dockerfile
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://cdn3.iconfinder.com/data/icons/virus-transmission-flat/48/Patient-512.png
      - THEME=DarkGray
      - PORT=3000
      - NAME=Patient
      - EMAIL=123456789@qq.com
      - PASSWORD=123
      - USERNAME=Patient
      - PUBLIC_DID_ENDPOINT=173.17.0.150:3000
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3000:3000
    depends_on:
      - node1
      - node2
      - node3
      - node4
    networks:
      services:
        ipv4_address: 173.17.0.150
    volumes:
      - node1-data:/home/indy/ledger

  #
  #
  Doctor:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://cdn3.iconfinder.com/data/icons/virus-transmission-flat/48/Doctor-256.png
      - THEME=BurlyWood
      - PORT=3001
      - NAME=Doctor
      - EMAIL=12345678@qq.com
      - PASSWORD=123
      - USERNAME=Doctor
      - PUBLIC_DID_ENDPOINT=173.17.0.160:3001
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3001:3001
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.160
    volumes:
      - node1-data:/home/indy/ledger

  regulators:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://cdn1.iconfinder.com/data/icons/monoflat-series-09/322/university-search-institution-analysis-bank-financial-256.png
      - THEME=OliveDrab
      - PORT=3002
      - NAME=regulators
      - EMAIL=1234567@qq.com
      - PASSWORD=123
      - USERNAME=regulators
      - PUBLIC_DID_ENDPOINT=173.17.0.170:3002
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3002:3002
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.170
    volumes:
      - node1-data:/home/indy/ledger

  pharmacy:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://cdn1.iconfinder.com/data/icons/supermarket-cafe-and-stores/50/14-256.png
      - THEME=LightSteelBlue
      - PORT=3003
      - NAME=pharmacy
      - EMAIL=123456@qq.com
      - PASSWORD=123
      - USERNAME=pharmacy
      - PUBLIC_DID_ENDPOINT=173.17.0.180:3003
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3003:3003
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.180
    volumes:
      - node1-data:/home/indy/ledger

  insurer:
    image: indy-agentjs
    command: "bash -c 'sleep 10; npm start'"
    environment:
      - ICON_SRC=https://cdn1.iconfinder.com/data/icons/data-science-flat-1/64/insurance-detecting-fraud-data-science-company-256.png
      - THEME=Coral
      - PORT=3004
      - NAME=insurer
      - EMAIL=12345@qq.com
      - PASSWORD=123
      - USERNAME=insurer
      - PUBLIC_DID_ENDPOINT=173.17.0.190:3004
      - RUST_LOG=${RUST_LOG}
      - TEST_POOL_IP=${TEST_POOL_IP}
    ports:
      - 3004:3004
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - alice
    networks:
      services:
        ipv4_address: 173.17.0.190
    volumes:
      - node1-data:/home/indy/ledger

volumes:
  webserver-cli:
  node1-data:
  node2-data:
  node3-data:
  node4-data:
